In [1]:
#Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, KFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import roc_curve, roc_auc_score

In [2]:
#File path to the zipped datafile
zip_path = '../../Data/Processed/Data_Compressed.zip'

#List of filenames to read from the zip file
filenames = [
    'Data_Compressed/all_normalized_features.csv',
    'Data_Compressed/kdd_all_normalized_features.csv',
    'Data_Compressed/kdd_expanded_all_scaled.csv',
    'Data_Compressed/kdd_merged_normalized_all.csv'
]

#Corresponding names for the DataFrames
df_names = [
    'xuetangx_df',
    'kdd_df',
    'kdd_expanded_df',
    'kdd_merged_df'
]

#Create an empty dictionary to store the DataFrames
dataframes = {}

#Open the zip file
z = zipfile.ZipFile(zip_path, 'r')

#Loop through the filenames and read them into DataFrames
for i, file in enumerate(filenames):
    print(f"Reading file: {file} from {zip_path}")
    
    #Read each CSV file directly from the zip
    f = z.open(file)
    dataframes[df_names[i]] = pd.read_csv(f)
    f.close()
    
    print(f"{df_names[i]} loaded with shape: {dataframes[df_names[i]].shape}\n")

#Close the zip file after reading
z.close()

#Assign individual DataFrames to variables
xuetangx_df = dataframes['xuetangx_df']
kdd_df = dataframes['kdd_df']
kdd_expanded_df = dataframes['kdd_expanded_df']
kdd_merged_df = dataframes['kdd_merged_df']

Reading file: Data_Compressed/all_normalized_features.csv from ../../Data/Processed/Data_Compressed.zip
xuetangx_df loaded with shape: (225642, 30)

Reading file: Data_Compressed/kdd_all_normalized_features.csv from ../../Data/Processed/Data_Compressed.zip
kdd_df loaded with shape: (200904, 17)

Reading file: Data_Compressed/kdd_expanded_all_scaled.csv from ../../Data/Processed/Data_Compressed.zip
kdd_expanded_df loaded with shape: (120542, 142)

Reading file: Data_Compressed/kdd_merged_normalized_all.csv from ../../Data/Processed/Data_Compressed.zip
kdd_merged_df loaded with shape: (120542, 158)

In [3]:
# %pip install tensorflow
# %pip install keras
# %pip install scikit-learn
# %pip install fastai
# %pip install torch

In [4]:
#Import required libraries for Deep Learning
#Keras DNN Classifier
from keras.models import Sequential
from keras.layers import BatchNormalization, Dense, Dropout, Input
from keras.regularizers import l2
from keras.utils import to_categorical, normalize
from keras import backend as K

#FastAI DL Classifier
import torch
from fastai.tabular.all import *

#Metrics for evaluation
from sklearn.metrics import balanced_accuracy_score, accuracy_score, precision_score, recall_score, roc_auc_score, f1_score
from sklearn.model_selection import train_test_split

### Data Preprocessing

In [5]:
#Display the info of the xuetangx_df DataFrame
xuetangx_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225642 entries, 0 to 225641
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   enroll_id                      225642 non-null  int64
 1   action_count                   225642 non-null  float64
 2   seek_video_count               225642 non-null  float64
 3   play_video_count               225642 non-null  float64
 4   pause_video_count              225642 non-null  float64
 5   stop_video_count               225642 non-null  float64
 6   load_video_count               225642 non-null  float64
 7   problem_get_count              225642 non-null  float64
 8   problem_check_count            225642 non-null  float64
 9   problem_save_count             225642 non-null  float64
 10  reset_problem_count            225642 non-null  float64
 11  problem_check_correct_count    225642 non-null  float64
 12  problem_check_incorrect_count  225642 non-null  float64
 13  create_thread_count            225642 non-null  float64
 14  create_comment_count           225642 non-null  float64
 15  delete_thread_count            225642 non-null  float64
 16  delete_comment_count           225642 non-null  float64
 17  click_info_count               225642 non-null  float64
 18  click_courseware_count         225642 non-null  float64
 19  click_about_count              225642 non-null  float64
 20  click_forum_count              225642 non-null  float64
 21  click_progress_count           225642 non-null  float64
 22  close_courseware_count         225642 non-null  float64
 23  truth                          225642 non-null  int64
 24  age                            225642 non-null  int64
 25  gender                         225642 non-null  int64
 26  education                      225642 non-null  int64
 27  user_enroll_count              225642 non-null  float64
 28  course_enroll_count            225642 non-null  float64
 29  course_category                225642 non-null  int64
dtypes: float64(24), int64(6)
memory usage: 51.6 MB

In [6]:
#Display the info of the kdd_df DataFrame
kdd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200904 entries, 0 to 200903
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   enrollment_id             200904 non-null  int64
 1   action_count              200904 non-null  float64
 2   server_navigate_count     200904 non-null  float64
 3   server_access_count       200904 non-null  float64
 4   server_problem_count      200904 non-null  float64
 5   server_page_close_count   200904 non-null  float64
 6   server_video_count        200904 non-null  float64
 7   server_discussion_count   200904 non-null  float64
 8   server_wiki_count         200904 non-null  float64
 9   browser_navigate_count    200904 non-null  float64
 10  browser_access_count      200904 non-null  float64
 11  browser_problem_count     200904 non-null  float64
 12  browser_page_close_count  200904 non-null  float64
 13  browser_video_count       200904 non-null  float64
 14  browser_discussion_count  200904 non-null  float64
 15  browser_wiki_count        200904 non-null  float64
 16  truth                     200904 non-null  int64
dtypes: float64(15), int64(2)
memory usage: 26.1 MB

In [7]:
#Display the info of the kdd_expanded_df DataFrame
kdd_expanded_df.columns

Index(['Unnamed: 0', 'enrollment_id', 'truth', 'avg_chapter_delays',
       'server_discussion_percent', 'act_cnt_weekDay_01',
       'browser_html_percent', 'parallel_enrollments', 'browser_dictation',
       'act_cnt_day_00',
       ...
       'server_course_percent', 'browser_course_info_percent',
       'browser_course', 'browser_vertical_percent', 'sessions_in_week_1',
       'sessions_in_week_0', 'sessions_in_week_3', 'sessions_in_week_2',
       'sessions_in_week_4', 'browser_about'],
      dtype='object', length=142)

In [8]:
#Isolate the X and y features for the xuetangx dataset
xuetangx_X = xuetangx_df.drop(columns=['truth'])
xuetangx_X = xuetangx_X.drop(columns=['enroll_id'])
xuetangx_y = xuetangx_df['truth']
#Isolate the X and y features for the kdd dataset
kdd_X = kdd_df.drop(columns=['truth'])
kdd_X = kdd_X.drop(columns=['enrollment_id'])
kdd_y = kdd_df['truth']
#Isolate the X and y features for the kdd_expanded 
kdd_expanded_X = kdd_expanded_df.drop(columns=['truth'])
kdd_expanded_X = kdd_expanded_X.drop(columns=['enrollment_id'])
kdd_expanded_X = kdd_expanded_X.drop(columns=['Unnamed: 0'])
kdd_expanded_y = kdd_expanded_df['truth']

In [9]:
#Split the xuetangx dataset into training and testing sets
xuetangx_X_train, xuetangx_X_test, xuetangx_y_train, xuetangx_y_test = train_test_split(xuetangx_X, xuetangx_y, test_size=0.2, random_state=100)

#Split the kdd dataset into training and testing sets
kdd_X_train, kdd_X_test, kdd_y_train, kdd_y_test = train_test_split(kdd_X, kdd_y, test_size=0.2, random_state=100)

#Split the kdd_expanded dataset into training and testing sets
kdd_expanded_X_train, kdd_expanded_X_test, kdd_expanded_y_train, kdd_expanded_y_test = train_test_split(kdd_expanded_X, kdd_expanded_y, test_size=0.2, random_state=100)

### Keras-TensorFlow

#### Xuetangx

In [10]:
#Modify the training and test variables to use the xuetangx dataset for readability
X_train, X_test, y_train, y_test = xuetangx_X_train, xuetangx_X_test, xuetangx_y_train, xuetangx_y_test

In [11]:
#Initialize KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

#Prepare results storage
results = {
    'Accuracy': [],
    'Balanced Accuracy': [],
    'Recall': [],
    'Precision': [],
    'AUC': [],
    'F1 Score': []
}

X_np = X_train.values
y_np = y_train.values

for train_index, val_index in kf.split(X_np):
    X_train_fold, X_val_fold = X_np[train_index], X_np[val_index]
    y_train_fold, y_val_fold = y_np[train_index], y_np[val_index]

    #Build and compile model
    model = Sequential([
        Dense(128, kernel_regularizer=l2(0.001), activation='relu', input_shape=(X_train.shape[1],)),
        BatchNormalization(),
        Dense(64, activation='relu', kernel_regularizer=l2(0.001)),
        BatchNormalization(),
        Dense(len(np.unique(y_train)), activation='softmax')
    ])
    
    model.compile(optimizer='adam', loss='categorical_crossentropy')

    #Convert y to one-hot for training
    y_train_cat = to_categorical(y_train_fold)
    
    #Fit the model
    model.fit(X_train_fold, y_train_cat, epochs=100, verbose=0, batch_size=512)

    #Predict and evaluate
    y_val_probs = model.predict(X_val_fold)
    y_pred = np.argmax(y_val_probs, axis=1)

    #Metrics
    acc = accuracy_score(y_val_fold, y_pred) * 100
    bal_acc = balanced_accuracy_score(y_val_fold, y_pred) * 100
    rec = recall_score(y_val_fold, y_pred, average='weighted') * 100
    prec = precision_score(y_val_fold, y_pred, average='weighted') * 100
    auc = roc_auc_score(y_val_fold, y_pred) * 100
    f1 = f1_score(y_val_fold, y_pred) * 100

    #Store metrics
    results['Accuracy'].append(acc)
    results['Balanced Accuracy'].append(bal_acc)
    results['Recall'].append(rec)
    results['Precision'].append(prec)
    results['AUC'].append(auc)
    results['F1 Score'].append(f1)

#Summarize results
summary = {
    metric: f"{np.mean(vals):.2f} ± {np.std(vals):.2f}"
    for metric, vals in results.items()
}

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

KeyboardInterrupt:

In [ ]:
#Store the results in the comparison DataFrame
xuetangx_tf_df = pd.DataFrame(list(summary.items()), columns=['Metric', 'Value'])
xuetangx_final_df = xuetangx_tf_df.set_index('Metric').T
xuetangx_final_df.index = ['Keras-Tensorflow'] 
print(xuetangx_final_df)

Metric                Accuracy Balanced Accuracy  ...           AUC      F1 Score
Keras-Tensorflow  83.72 ± 0.09      72.35 ± 0.67  ...  72.35 ± 0.67  89.78 ± 0.06

[1 rows x 6 columns]

#### KDD (Experiment 1)

In [ ]:
#Modify the training and test variables to use the xuetangx dataset for readability
X_train, X_test, y_train, y_test = kdd_X_train, kdd_X_test, kdd_y_train, kdd_y_test

In [ ]:
#Initialize KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

#Prepare results storage
results = {
    'Accuracy': [],
    'Balanced Accuracy': [],
    'Recall': [],
    'Precision': [],
    'AUC': [],
    'F1 Score': []
}

X_np = X_train.values
y_np = y_train.values

for train_index, val_index in kf.split(X_np):
    X_train_fold, X_val_fold = X_np[train_index], X_np[val_index]
    y_train_fold, y_val_fold = y_np[train_index], y_np[val_index]

    #Build and compile model
    model = Sequential([
        Dense(128, kernel_regularizer=l2(0.001), activation='relu', input_shape=(X_train.shape[1],)),
        BatchNormalization(),
        Dense(64, activation='relu', kernel_regularizer=l2(0.001)),
        BatchNormalization(),
        Dense(len(np.unique(y_train)), activation='softmax')
    ])
    
    model.compile(optimizer='adam', loss='categorical_crossentropy')

    #Convert y to one-hot for training
    y_train_cat = to_categorical(y_train_fold)
    
    #Fit the model
    model.fit(X_train_fold, y_train_cat, epochs=100, verbose=0, batch_size=512)

    #Predict and evaluate
    y_val_probs = model.predict(X_val_fold)
    y_pred = np.argmax(y_val_probs, axis=1)

    #Metrics
    acc = accuracy_score(y_val_fold, y_pred) * 100
    bal_acc = balanced_accuracy_score(y_val_fold, y_pred) * 100
    rec = recall_score(y_val_fold, y_pred, average='weighted') * 100
    prec = precision_score(y_val_fold, y_pred, average='weighted') * 100
    auc = roc_auc_score(y_val_fold, y_pred) * 100
    f1 = f1_score(y_val_fold, y_pred) * 100

    #Store metrics
    results['Accuracy'].append(acc)
    results['Balanced Accuracy'].append(bal_acc)
    results['Recall'].append(rec)
    results['Precision'].append(prec)
    results['AUC'].append(auc)
    results['F1 Score'].append(f1)

#Summarize results
summary = {
    metric: f"{np.mean(vals):.2f} ± {np.std(vals):.2f}"
    for metric, vals in results.items()
}

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1005/1005 ━━━━━━━━━━━━━━━━━━━━ 1s 521us/step

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1005/1005 ━━━━━━━━━━━━━━━━━━━━ 1s 523us/step

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1005/1005 ━━━━━━━━━━━━━━━━━━━━ 1s 507us/step

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1005/1005 ━━━━━━━━━━━━━━━━━━━━ 1s 606us/step

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1005/1005 ━━━━━━━━━━━━━━━━━━━━ 1s 528us/step

In [ ]:
#Store the results in the comparison DataFrame
kdd_tf_df = pd.DataFrame(list(summary.items()), columns=['Metric', 'Value'])
kdd_final_df = kdd_tf_df.set_index('Metric').T
kdd_final_df.index = ['Keras-Tensorflow'] 
print(kdd_final_df)

Metric                Accuracy Balanced Accuracy  ...           AUC      F1 Score
Keras-Tensorflow  86.02 ± 0.10      72.30 ± 0.47  ...  72.30 ± 0.47  91.56 ± 0.06

[1 rows x 6 columns]

#### KDD (Experiment 2)

In [ ]:
#Modify the training and test variables to use the xuetangx dataset for readability
X_train, X_test, y_train, y_test = kdd_expanded_X_train, kdd_expanded_X_test, kdd_expanded_y_train, kdd_expanded_y_test

In [ ]:
#Initialize KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

#Prepare results storage
results = {
    'Accuracy': [],
    'Balanced Accuracy': [],
    'Recall': [],
    'Precision': [],
    'AUC': [],
    'F1 Score': []
}

X_np = X_train.values
y_np = y_train.values

for train_index, val_index in kf.split(X_np):
    X_train_fold, X_val_fold = X_np[train_index], X_np[val_index]
    y_train_fold, y_val_fold = y_np[train_index], y_np[val_index]

    #Build and compile model
    model = Sequential([
        Dense(128, kernel_regularizer=l2(0.001), activation='relu', input_shape=(X_train.shape[1],)),
        BatchNormalization(),
        Dense(64, activation='relu', kernel_regularizer=l2(0.001)),
        BatchNormalization(),
        Dense(len(np.unique(y_train)), activation='softmax')
    ])
    
    model.compile(optimizer='adam', loss='categorical_crossentropy')

    #Convert y to one-hot for training
    y_train_cat = to_categorical(y_train_fold)
    
    #Fit the model
    model.fit(X_train_fold, y_train_cat, epochs=100, verbose=0, batch_size=512)

    #Predict and evaluate
    y_val_probs = model.predict(X_val_fold)
    y_pred = np.argmax(y_val_probs, axis=1)

    #Metrics
    acc = accuracy_score(y_val_fold, y_pred) * 100
    bal_acc = balanced_accuracy_score(y_val_fold, y_pred) * 100
    rec = recall_score(y_val_fold, y_pred, average='weighted') * 100
    prec = precision_score(y_val_fold, y_pred, average='weighted') * 100
    auc = roc_auc_score(y_val_fold, y_pred) * 100
    f1 = f1_score(y_val_fold, y_pred) * 100

    #Store metrics
    results['Accuracy'].append(acc)
    results['Balanced Accuracy'].append(bal_acc)
    results['Recall'].append(rec)
    results['Precision'].append(prec)
    results['AUC'].append(auc)
    results['F1 Score'].append(f1)

#Summarize results
summary = {
    metric: f"{np.mean(vals):.2f} ± {np.std(vals):.2f}"
    for metric, vals in results.items()
}

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

603/603 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

603/603 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

603/603 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

603/603 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

603/603 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step

In [ ]:
#Store the results in the comparison DataFrame
kdd_expanded_tf_df = pd.DataFrame(list(summary.items()), columns=['Metric', 'Value'])
kdd_expanded_final_df = kdd_expanded_tf_df.set_index('Metric').T
kdd_expanded_final_df.index = ['Keras-Tensorflow'] 
print(kdd_expanded_final_df)

Metric                Accuracy Balanced Accuracy  ...           AUC      F1 Score
Keras-Tensorflow  85.66 ± 0.15      73.71 ± 0.53  ...  73.71 ± 0.53  91.24 ± 0.11

[1 rows x 6 columns]

### FastAI

#### Xuetangx

In [ ]:
#Modify the training and test variables to use the xuetangx dataset for readability
X_train, X_test, y_train, y_test = xuetangx_X_train, xuetangx_X_test, xuetangx_y_train, xuetangx_y_test

In [ ]:
#Create a DNN model using FastAI
#Initialize results dictionary first
results = {
    'Accuracy': [],
    'Balanced Accuracy': [],
    'Recall': [],
    'Precision': [],
    'AUC': [],
    'F1 Score': []
}

splits = RandomSplitter(valid_pct=0.2)(range_of(X_train))
X = X_train.copy()
X['truth'] = y_train.values
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_idx, val_idx in kf.split(X):
    train_df = X.iloc[train_idx].copy()
    val_df = X.iloc[val_idx].copy()

    #FastAI Tabular setup
    splits = (list(range(len(train_df))), list(range(len(train_df), len(train_df) + len(val_df))))
    full_df = pd.concat([train_df, val_df])
    
    tp = TabularPandas(
        full_df,
        procs=[],
        cont_names=list(X_train.columns),
        y_names='truth',
        splits=splits
    )

    dls = tp.dataloaders(bs=64)

    learn = tabular_learner(dls, metrics=accuracy)
    learn.fit_one_cycle(5)
    
    # Predictions
    X_val = val_df.drop(columns='truth')
    y_true = val_df['truth'].values
    dl_test = learn.dls.test_dl(X_val)
    
    preds = learn.get_preds(dl=dl_test)[0]
    
    y_pred = (preds >= 0.5).int().numpy()
    
    #Metrics
    results['Accuracy'].append(accuracy_score(y_true, y_pred) * 100)
    results['Balanced Accuracy'].append(balanced_accuracy_score(y_true, y_pred) * 100)
    results['Recall'].append(recall_score(y_true, y_pred, average='weighted') * 100)
    results['Precision'].append(precision_score(y_true, y_pred, average='weighted') * 100)
    results['AUC'].append(roc_auc_score(y_true, y_pred) * 100)
    results['F1 Score'].append(f1_score(y_true, y_pred) * 100)
    results['F1 Score'].append(f1_score(y_true, y_pred) * 100)

#Summarize results
summary = {
    metric: f"{np.mean(vals):.2f} ± {np.std(vals):.2f}"
    for metric, vals in results.items()
}

In [ ]:
#Store the results in the comparison DataFrame
xuetangx_fai_df = pd.DataFrame(list(summary.items()), columns=['Metric', 'Value'])
xuetangx_fai_df = xuetangx_fai_df.set_index('Metric').T
xuetangx_fai_df.index = ['Fast.AI']
#Append the results to the existing DataFrame
xuetangx_final_df = pd.concat([xuetangx_final_df, xuetangx_fai_df], axis=0)
print(xuetangx_final_df)

Metric                Accuracy Balanced Accuracy  ...           AUC      F1 Score
Keras-Tensorflow  83.72 ± 0.09      72.35 ± 0.67  ...  72.35 ± 0.67  89.78 ± 0.06
Fast.AI           83.34 ± 0.21      69.85 ± 0.83  ...  69.85 ± 0.83  89.73 ± 0.09

[2 rows x 6 columns]

#### KDD (Experiment 1)

In [ ]:
#Modify the training and test variables to use the kdd dataset for readability
X_train, X_test, y_train, y_test = kdd_X_train, kdd_X_test, kdd_y_train, kdd_y_test

In [ ]:
#Create a DNN model using FastAI
#Initialize results dictionary first
results = {
    'Accuracy': [],
    'Balanced Accuracy': [],
    'Recall': [],
    'Precision': [],
    'AUC': [],
    'F1 Score': []
}

splits = RandomSplitter(valid_pct=0.2)(range_of(X_train))
X = X_train.copy()
X['truth'] = y_train.values
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_idx, val_idx in kf.split(X):
    train_df = X.iloc[train_idx].copy()
    val_df = X.iloc[val_idx].copy()

    #FastAI Tabular setup
    splits = (list(range(len(train_df))), list(range(len(train_df), len(train_df) + len(val_df))))
    full_df = pd.concat([train_df, val_df])
    
    tp = TabularPandas(
        full_df,
        procs=[],
        cont_names=list(X_train.columns),
        y_names='truth',
        splits=splits
    )

    dls = tp.dataloaders(bs=64)

    learn = tabular_learner(dls, metrics=accuracy)
    learn.fit_one_cycle(5)
    
    #Predictions
    X_val = val_df.drop(columns='truth')
    y_true = val_df['truth'].values
    dl_test = learn.dls.test_dl(X_val)
    
    preds = learn.get_preds(dl=dl_test)[0]
    
    #For binary classification
    y_pred = (preds >= 0.5).int().numpy()
    
    #Metrics
    results['Accuracy'].append(accuracy_score(y_true, y_pred) * 100)
    results['Balanced Accuracy'].append(balanced_accuracy_score(y_true, y_pred) * 100)
    results['Recall'].append(recall_score(y_true, y_pred, average='weighted') * 100)
    results['Precision'].append(precision_score(y_true, y_pred, average='weighted') * 100)
    results['AUC'].append(roc_auc_score(y_true, y_pred) * 100)
    results['F1 Score'].append(f1_score(y_true, y_pred) * 100)
    results['F1 Score'].append(f1_score(y_true, y_pred) * 100)

#Summarize results
summary = {
    metric: f"{np.mean(vals):.2f} ± {np.std(vals):.2f}"
    for metric, vals in results.items()
}

In [ ]:
#Store the results in the comparison DataFrame
kdd_fai_df = pd.DataFrame(list(summary.items()), columns=['Metric', 'Value'])
kdd_fai_df = kdd_fai_df.set_index('Metric').T
kdd_fai_df.index = ['Fast.AI']
#Append the results to the existing DataFrame
kdd_final_df = pd.concat([kdd_final_df, kdd_fai_df], axis=0)
print(kdd_final_df)

Metric                Accuracy Balanced Accuracy  ...           AUC      F1 Score
Keras-Tensorflow  86.02 ± 0.10      72.30 ± 0.47  ...  72.30 ± 0.47  91.56 ± 0.06
Fast.AI           85.93 ± 0.13      71.87 ± 0.60  ...  71.87 ± 0.60  91.53 ± 0.07

[2 rows x 6 columns]

#### KDD (Experiment 2)

In [ ]:
#Modify the training and test variables to use the kdd_expanded dataset for readability
X_train, X_test, y_train, y_test = kdd_expanded_X_train, kdd_expanded_X_test, kdd_expanded_y_train, kdd_expanded_y_test

In [ ]:
#Create a DNN model using FastAI
#Initialize results dictionary first
results = {
    'Accuracy': [],
    'Balanced Accuracy': [],
    'Recall': [],
    'Precision': [],
    'AUC': [],
    'F1 Score': []
}

splits = RandomSplitter(valid_pct=0.2)(range_of(X_train))
X = X_train.copy()
X['truth'] = y_train.values
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_idx, val_idx in kf.split(X):
    train_df = X.iloc[train_idx].copy()
    val_df = X.iloc[val_idx].copy()

    #FastAI Tabular setup
    splits = (list(range(len(train_df))), list(range(len(train_df), len(train_df) + len(val_df))))
    full_df = pd.concat([train_df, val_df])
    
    tp = TabularPandas(
        full_df,
        procs=[],
        cat_names=[],  # If you have categorical features, add them here
        cont_names=list(X_train.columns),
        y_names='truth',
        splits=splits
    )

    dls = tp.dataloaders(bs=64)

    learn = tabular_learner(dls, metrics=accuracy)
    learn.fit_one_cycle(5)
    
    # Predictions
    X_val = val_df.drop(columns='truth')
    y_true = val_df['truth'].values
    dl_test = learn.dls.test_dl(X_val)
    
    # Fix: get_preds returns a tuple, extract just the predictions
    preds = learn.get_preds(dl=dl_test)[0]
    
    # For binary classification
    y_pred = (preds >= 0.5).int().numpy()
    
    #Metrics
    results['Accuracy'].append(accuracy_score(y_true, y_pred) * 100)
    results['Balanced Accuracy'].append(balanced_accuracy_score(y_true, y_pred) * 100)
    results['Recall'].append(recall_score(y_true, y_pred, average='weighted') * 100)
    results['Precision'].append(precision_score(y_true, y_pred, average='weighted') * 100)
    results['AUC'].append(roc_auc_score(y_true, y_pred) * 100)
    results['F1 Score'].append(f1_score(y_true, y_pred) * 100)
    results['F1 Score'].append(f1_score(y_true, y_pred) * 100)

#Summarize results
summary = {
    metric: f"{np.mean(vals):.2f} ± {np.std(vals):.2f}"
    for metric, vals in results.items()
}

In [ ]:
#Store the results in the comparison DataFrame
kdd_expanded_fai_df = pd.DataFrame(list(summary.items()), columns=['Metric', 'Value'])
kdd_expanded_fai_df = kdd_expanded_fai_df.set_index('Metric').T
kdd_expanded_fai_df.index = ['Fast.AI']
#Append the results to the existing DataFrame
kdd_expanded_final_df = pd.concat([kdd_expanded_final_df, kdd_expanded_fai_df], axis=0)
print(kdd_expanded_final_df)

Metric                Accuracy Balanced Accuracy  ...           AUC      F1 Score
Keras-Tensorflow  85.66 ± 0.15      73.71 ± 0.53  ...  73.71 ± 0.53  91.24 ± 0.11
Fast.AI           87.44 ± 0.18      75.77 ± 0.51  ...  75.77 ± 0.51  92.36 ± 0.11

[2 rows x 6 columns]

In [ ]:
#Display the final comparison DataFrame for all three datasets
display(xuetangx_final_df)
display(kdd_final_df)
display(kdd_expanded_final_df)

Metric                Accuracy Balanced Accuracy  ...           AUC      F1 Score
Keras-Tensorflow  83.72 ± 0.09      72.35 ± 0.67  ...  72.35 ± 0.67  89.78 ± 0.06
Fast.AI           83.34 ± 0.21      69.85 ± 0.83  ...  69.85 ± 0.83  89.73 ± 0.09

[2 rows x 6 columns]

Metric                Accuracy Balanced Accuracy  ...           AUC      F1 Score
Keras-Tensorflow  86.02 ± 0.10      72.30 ± 0.47  ...  72.30 ± 0.47  91.56 ± 0.06
Fast.AI           85.93 ± 0.13      71.87 ± 0.60  ...  71.87 ± 0.60  91.53 ± 0.07

[2 rows x 6 columns]

Metric                Accuracy Balanced Accuracy  ...           AUC      F1 Score
Keras-Tensorflow  85.66 ± 0.15      73.71 ± 0.53  ...  73.71 ± 0.53  91.24 ± 0.11
Fast.AI           87.44 ± 0.18      75.77 ± 0.51  ...  75.77 ± 0.51  92.36 ± 0.11

[2 rows x 6 columns]

In [ ]:
folder_path = '../../Analysis/Deep_Learning_Results'
xuetangx_final_df.to_csv(os.path.join(folder_path, 'xuetangx_final_results.csv'))
kdd_final_df.to_csv(os.path.join(folder_path, 'kdd_final_results.csv'))
kdd_expanded_final_df.to_csv(os.path.join(folder_path, 'kdd_expanded_final_results.csv'))

## SVM

Implemented for team members due to having more computational resources. Results are saved as csv files in the `Analysis` folder for members to append to their own results.

### Xuetangx SVM

In [10]:
#Modify the training and test variables to use the xuetangx dataset for readability
X_train, X_test, y_train, y_test = xuetangx_X_train, xuetangx_X_test, xuetangx_y_train, xuetangx_y_test

In [11]:
#Define the model
svc = SVC(gamma='auto')
#Define the KFold cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=42)
#Perform cross-validation
scores = cross_val_score(svc, X_train, y_train, cv=kf, scoring='accuracy', n_jobs=-1)
#Calculate the mean and standard deviation of the scores
mean_acc = np.mean(scores)
std_acc = np.std(scores)

In [16]:
#Store the results into a dataframe
xuetangx_svm_df = pd.DataFrame([{
    'Classifiers': 'SVM',
    'Mean Accuracy': round(mean_acc, 5),
    'SD': round(std_acc, 5)
}])

In [17]:
#Save the results to a new CSV file
folder_path = '../../Analysis/SVM_Results'
xuetangx_svm_df.to_csv(os.path.join(folder_path, 'xuetangx_svm_results.csv'))

#### KDD (Experiment 1) SVM

In [ ]:
#Modify the training and test variables to use the kdd dataset for readability
X_train, X_test, y_train, y_test = kdd_X_train, kdd_X_test, kdd_y_train, kdd_y_test

In [ ]:
#Define the model
svc = SVC(gamma='auto')
#Define the KFold cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=42)
#Perform cross-validation
scores = cross_val_score(svc, X_train, y_train, cv=kf, scoring='accuracy', n_jobs=-1)
#Calculate the mean and standard deviation of the scores
mean_acc = np.mean(scores)
std_acc = np.std(scores)

In [ ]:
#Store the results into a dataframe
kdd_svm_df = pd.DataFrame([{
    'Classifiers': 'SVM',
    'Mean Accuracy': round(mean_acc, 5),
    'SD': round(std_acc, 5)
}])

In [ ]:
#Save the results to a new CSV file
folder_path = '../../Analysis/SVM_Results'
kdd_svm_df.to_csv(os.path.join(folder_path, 'kdd_svm_results.csv'))

### KDD (Experiment 2) SVM

In [ ]:
#Modify the training and test variables to use the kdd_expanded dataset for readability
X_train, X_test, y_train, y_test = kdd_expanded_X_train, kdd_expanded_X_test, kdd_expanded_y_train, kdd_expanded_y_test

In [ ]:
#Define the model
svc = SVC(gamma='auto')
#Define the KFold cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=42)
#Perform cross-validation
scores = cross_val_score(svc, X_train, y_train, cv=kf, scoring='accuracy', n_jobs=-1)
#Calculate the mean and standard deviation of the scores
mean_acc = np.mean(scores)
std_acc = np.std(scores)

In [ ]:
#Store the results into a dataframe
kdd_expanded_svm_df = pd.DataFrame([{
    'Classifiers': 'SVM',
    'Mean Accuracy': round(mean_acc, 5),
    'SD': round(std_acc, 5)
}])

In [ ]:
#Save the results to a new CSV file
folder_path = '../../Analysis/SVM_Results'
kdd_expanded_svm_df.to_csv(os.path.join(folder_path, 'kdd_expanded_svm_results.csv'))