## Creating the Notebook and importing in Data from the Group Github

In [1]:
#Import Initial libraries

#Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile

In [2]:
#Run code provided by Chance for consitent notebooks within the group

#File path to the zipped datafile
zip_path = '../../Data/Processed/Data_Compressed.zip'

#List of filenames to read from the zip file
filenames = [
    'Data_Compressed/all_normalized_features.csv',
    'Data_Compressed/kdd_all_normalized_features.csv',
    'Data_Compressed/kdd_expanded_all_scaled.csv',
    'Data_Compressed/kdd_merged_normalized_all.csv'
]

#Corresponding names for the DataFrames
df_names = [
    'xuetangx_df',
    'kdd_df',
    'kdd_expanded_df',
    'kdd_merged_df'
]

#Create an empty dictionary to store the DataFrames
dataframes = {}

#Open the zip file
z = zipfile.ZipFile(zip_path, 'r')

#Loop through the filenames and read them into DataFrames
for i, file in enumerate(filenames):
    print(f"Reading file: {file} from {zip_path}")
    
    #Read each CSV file directly from the zip
    f = z.open(file)
    dataframes[df_names[i]] = pd.read_csv(f)
    f.close()
    
    print(f"{df_names[i]} loaded with shape: {dataframes[df_names[i]].shape}\n")

#Close the zip file after reading
z.close()

#Assign individual DataFrames to variables
xuetangx_df = dataframes['xuetangx_df']
kdd_df = dataframes['kdd_df']
kdd_expanded_df = dataframes['kdd_expanded_df']
kdd_merged_df = dataframes['kdd_merged_df']

Reading file: Data_Compressed/all_normalized_features.csv from ../../Data/Processed/Data_Compressed.zip
xuetangx_df loaded with shape: (225642, 30)

Reading file: Data_Compressed/kdd_all_normalized_features.csv from ../../Data/Processed/Data_Compressed.zip
kdd_df loaded with shape: (200904, 17)

Reading file: Data_Compressed/kdd_expanded_all_scaled.csv from ../../Data/Processed/Data_Compressed.zip
kdd_expanded_df loaded with shape: (120542, 142)

Reading file: Data_Compressed/kdd_merged_normalized_all.csv from ../../Data/Processed/Data_Compressed.zip
kdd_merged_df loaded with shape: (120542, 158)

## Reproduction of the 2nd Experiment with Machine Learning Models
- Use larger feature set (140 features) generarated by Peng and Aggarwal
  - kdd_expanded_df

In [3]:
#View the basic info for the data set before starting toensure proper importation

kdd_expanded_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120542 entries, 0 to 120541
Data columns (total 142 columns):
 #    Column                             Dtype
---   ------                             -----
 0    Unnamed: 0                         int64
 1    enrollment_id                      int64
 2    truth                              int64
 3    avg_chapter_delays                 float64
 4    server_discussion_percent          int64
 5    act_cnt_weekDay_01                 float64
 6    browser_html_percent               int64
 7    parallel_enrollments               float64
 8    browser_dictation                  int64
 9    act_cnt_day_00                     int64
 10   act_cnt_day_01                     float64
 11   act_cnt_day_02                     float64
 12   act_cnt_day_03                     float64
 13   act_cnt_day_04                     float64
 14   act_cnt_day_05                     float64
 15   act_cnt_day_06                     float64
 16   act_cnt_day_07                     float64
 17   act_cnt_day_08                     float64
 18   act_cnt_day_09                     float64
 19   server_sequential                  float64
 20   server_combinedopenended_percent   int64
 21   browser_discussion_percent         int64
 22   browser_wiki                       int64
 23   browser_outlink_percent            int64
 24   server_peergrading                 int64
 25   browser_about_percent              int64
 26   browser_outlink                    int64
 27   act_cnt_day_19                     float64
 28   act_cnt_day_18                     float64
 29   act_cnt_day_17                     float64
 30   act_cnt_day_16                     float64
 31   act_cnt_day_15                     float64
 32   act_cnt_day_14                     float64
 33   act_cnt_day_13                     float64
 34   act_cnt_day_12                     float64
 35   act_cnt_day_11                     float64
 36   act_cnt_day_10                     float64
 37   act_cnt_day_29                     float64
 38   wiki                               float64
 39   browser_problem                    float64
 40   server_peergrading_percent         int64
 41   server_video_percent               int64
 42   server_outlink                     int64
 43   act_cnt_weekDay_04                 float64
 44   act_cnt_weekDay_05                 float64
 45   act_cnt_weekDay_06                 float64
 46   server_wiki                        float64
 47   act_cnt_weekDay_00                 float64
 48   server_vertical                    int64
 49   act_cnt_weekDay_02                 float64
 50   act_cnt_weekDay_03                 float64
 51   access                             float64
 52   browser_combinedopenended          float64
 53   server_course                      int64
 54   browser_access                     float64
 55   browser_course_info                int64
 56   server_about_percent               int64
 57   browser_static_tab                 int64
 58   server_chapter_percent             float64
 59   browser_video                      float64
 60   browser_peergrading                int64
 61   browser_navigate                   int64
 62   browser_vertical                   int64
 63   browser_dictation_percent          int64
 64   server_vertical_percent            int64
 65   server_about                       int64
 66   browser_sequential_percent         float64
 67   browser_combinedopenended_percent  float64
 68   server_course_info_percent         int64
 69   server_html                        int64
 70   browser_html                       int64
 71   server_problem_percent             float64
 72   browser_discussion                 int64
 73   server_static_tab_percent          int64
 74   act_cnt_hour_22                    float64
 75   browser_chapter_percent            int64
 76   class_size                         float64
 77   server_combinedopenended           int64
 78   browser_course_percent             int64
 79   server_sequential_percent          float64
 80   act_cnt_hour_03                    float64
 81   act_cnt_hour_02                    float64
 82   act_cnt_hour_01                    float64
 83   act_cnt_hour_00                    float64
 84   act_cnt_hour_07                    float64
 85   act_cnt_hour_06                    float64
 86   act_cnt_hour_05                    float64
 87   act_cnt_hour_04                    float64
 88   act_cnt_hour_09                    float64
 89   act_cnt_hour_08                    float64
 90   browser_static_tab_percent         int64
 91   server_video                       int64
 92   browser_video_percent              float64
 93   server_discussion                  int64
 94   navigate                           float64
 95   server_static_tab                  int64
 96   server_course_info                 int64
 97   server_problem                     float64
 98   act_cnt_hour_10                    float64
 99   act_cnt_hour_11                    float64
 100  act_cnt_hour_12                    float64
 101  act_cnt_hour_13                    float64
 102  act_cnt_hour_14                    float64
 103  act_cnt_hour_15                    float64
 104  act_cnt_hour_16                    float64
 105  act_cnt_hour_17                    float64
 106  act_cnt_hour_18                    float64
 107  act_cnt_hour_19                    float64
 108  server_html_percent                int64
 109  act_cnt_day_26                     float64
 110  act_cnt_day_27                     float64
 111  act_cnt_day_24                     float64
 112  act_cnt_day_25                     float64
 113  act_cnt_day_22                     float64
 114  act_cnt_day_23                     float64
 115  act_cnt_day_20                     float64
 116  act_cnt_day_21                     float64
 117  server_chapter                     float64
 118  act_cnt_day_28                     float64
 119  act_cnt_day_30                     float64
 120  server_navigate                    float64
 121  server_dictation                   int64
 122  browser_peergrading_percent        int64
 123  browser_problem_percent            float64
 124  browser_sequential                 float64
 125  browser_chapter                    int64
 126  server_dictation_percent           int64
 127  act_cnt_hour_21                    float64
 128  act_cnt_hour_20                    float64
 129  act_cnt_hour_23                    float64
 130  server_access                      float64
 131  server_outlink_percent             int64
 132  server_course_percent              int64
 133  browser_course_info_percent        int64
 134  browser_course                     int64
 135  browser_vertical_percent           int64
 136  sessions_in_week_1                 float64
 137  sessions_in_week_0                 float64
 138  sessions_in_week_3                 float64
 139  sessions_in_week_2                 float64
 140  sessions_in_week_4                 float64
 141  browser_about                      int64
dtypes: float64(90), int64(52)
memory usage: 130.6 MB

In [4]:
#View header information for Kdd-expanded
kdd_expanded_df.head()

,Unnamed: 0,enrollment_id,truth,avg_chapter_delays,server_discussion_percent,act_cnt_weekDay_01,browser_html_percent,parallel_enrollments,browser_dictation,act_cnt_day_00,...,server_course_percent,browser_course_info_percent,browser_course,browser_vertical_percent,sessions_in_week_1,sessions_in_week_0,sessions_in_week_3,sessions_in_week_2,sessions_in_week_4,browser_about
0,0,1,0,0.401837,0,0.317621,0,3.960922,0,0,...,0,0,0,0,2.076406,-0.029110,1.685275,2.636167,2.141673,0
1,1,3,0,0.460054,0,-0.005913,0,-0.449933,0,0,...,0,0,0,0,0.565552,0.466433,0.126527,0.087058,0.928388,0
2,2,4,0,0.866122,0,-0.094149,0,0.652780,0,0,...,0,0,0,0,1.572788,1.457518,-0.393056,2.126345,-0.284897,0
3,3,5,0,0.429975,0,1.964698,0,-0.449933,0,0,...,0,0,0,0,7.616205,0.466433,6.361519,0.087058,4.568243,0
4,4,6,0,-0.255399,0,-0.123561,0,-0.449933,0,0,...,0,0,0,0,-0.441684,-0.524652,0.126527,-0.422764,2.141673,0

### Importing Additional Libraries for modeling

In [13]:
# ImportModels based on the Jupyter Notebook on Github related to the paper and modeling experiments
## https://github.com/rambasnet/PredictingMOOCDropouts/blob/master/KDD_experiments.ipynb

# Additional Scikit-Learn imports
from sklearn.model_selection import StratifiedKFold

# Scikit-Learn's ML models
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB

# Had assistance from the Anaconda AI Assistant due to needing to pip install the library first
import xgboost as xgb
from xgboost import XGBClassifier

#Importing additional pieces of sklearn that may be needed 
## These imports are based on modeling in DATA6320
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import roc_curve, roc_auc_score

In [14]:
#Create the X and Y data sets
# 'truth' is the variable for dropout rate as seen in the original code from the research
y= kdd_expanded_df['truth']
display(y.value_counts())
display(round(y.value_counts(normalize=True),3))

truth
1    95581
0    24961
Name: count, dtype: int64

truth
1    0.793
0    0.207
Name: proportion, dtype: float64

In [15]:
#Create the X data set with by dropping columns that do not belong in the model BurgStatus

X = kdd_expanded_df.drop (['truth','Unnamed: 0','enrollment_id'], axis=1)
X.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120542 entries, 0 to 120541
Data columns (total 139 columns):
 #    Column                             Dtype
---   ------                             -----
 0    avg_chapter_delays                 float64
 1    server_discussion_percent          int64
 2    act_cnt_weekDay_01                 float64
 3    browser_html_percent               int64
 4    parallel_enrollments               float64
 5    browser_dictation                  int64
 6    act_cnt_day_00                     int64
 7    act_cnt_day_01                     float64
 8    act_cnt_day_02                     float64
 9    act_cnt_day_03                     float64
 10   act_cnt_day_04                     float64
 11   act_cnt_day_05                     float64
 12   act_cnt_day_06                     float64
 13   act_cnt_day_07                     float64
 14   act_cnt_day_08                     float64
 15   act_cnt_day_09                     float64
 16   server_sequential                  float64
 17   server_combinedopenended_percent   int64
 18   browser_discussion_percent         int64
 19   browser_wiki                       int64
 20   browser_outlink_percent            int64
 21   server_peergrading                 int64
 22   browser_about_percent              int64
 23   browser_outlink                    int64
 24   act_cnt_day_19                     float64
 25   act_cnt_day_18                     float64
 26   act_cnt_day_17                     float64
 27   act_cnt_day_16                     float64
 28   act_cnt_day_15                     float64
 29   act_cnt_day_14                     float64
 30   act_cnt_day_13                     float64
 31   act_cnt_day_12                     float64
 32   act_cnt_day_11                     float64
 33   act_cnt_day_10                     float64
 34   act_cnt_day_29                     float64
 35   wiki                               float64
 36   browser_problem                    float64
 37   server_peergrading_percent         int64
 38   server_video_percent               int64
 39   server_outlink                     int64
 40   act_cnt_weekDay_04                 float64
 41   act_cnt_weekDay_05                 float64
 42   act_cnt_weekDay_06                 float64
 43   server_wiki                        float64
 44   act_cnt_weekDay_00                 float64
 45   server_vertical                    int64
 46   act_cnt_weekDay_02                 float64
 47   act_cnt_weekDay_03                 float64
 48   access                             float64
 49   browser_combinedopenended          float64
 50   server_course                      int64
 51   browser_access                     float64
 52   browser_course_info                int64
 53   server_about_percent               int64
 54   browser_static_tab                 int64
 55   server_chapter_percent             float64
 56   browser_video                      float64
 57   browser_peergrading                int64
 58   browser_navigate                   int64
 59   browser_vertical                   int64
 60   browser_dictation_percent          int64
 61   server_vertical_percent            int64
 62   server_about                       int64
 63   browser_sequential_percent         float64
 64   browser_combinedopenended_percent  float64
 65   server_course_info_percent         int64
 66   server_html                        int64
 67   browser_html                       int64
 68   server_problem_percent             float64
 69   browser_discussion                 int64
 70   server_static_tab_percent          int64
 71   act_cnt_hour_22                    float64
 72   browser_chapter_percent            int64
 73   class_size                         float64
 74   server_combinedopenended           int64
 75   browser_course_percent             int64
 76   server_sequential_percent          float64
 77   act_cnt_hour_03                    float64
 78   act_cnt_hour_02                    float64
 79   act_cnt_hour_01                    float64
 80   act_cnt_hour_00                    float64
 81   act_cnt_hour_07                    float64
 82   act_cnt_hour_06                    float64
 83   act_cnt_hour_05                    float64
 84   act_cnt_hour_04                    float64
 85   act_cnt_hour_09                    float64
 86   act_cnt_hour_08                    float64
 87   browser_static_tab_percent         int64
 88   server_video                       int64
 89   browser_video_percent              float64
 90   server_discussion                  int64
 91   navigate                           float64
 92   server_static_tab                  int64
 93   server_course_info                 int64
 94   server_problem                     float64
 95   act_cnt_hour_10                    float64
 96   act_cnt_hour_11                    float64
 97   act_cnt_hour_12                    float64
 98   act_cnt_hour_13                    float64
 99   act_cnt_hour_14                    float64
 100  act_cnt_hour_15                    float64
 101  act_cnt_hour_16                    float64
 102  act_cnt_hour_17                    float64
 103  act_cnt_hour_18                    float64
 104  act_cnt_hour_19                    float64
 105  server_html_percent                int64
 106  act_cnt_day_26                     float64
 107  act_cnt_day_27                     float64
 108  act_cnt_day_24                     float64
 109  act_cnt_day_25                     float64
 110  act_cnt_day_22                     float64
 111  act_cnt_day_23                     float64
 112  act_cnt_day_20                     float64
 113  act_cnt_day_21                     float64
 114  server_chapter                     float64
 115  act_cnt_day_28                     float64
 116  act_cnt_day_30                     float64
 117  server_navigate                    float64
 118  server_dictation                   int64
 119  browser_peergrading_percent        int64
 120  browser_problem_percent            float64
 121  browser_sequential                 float64
 122  browser_chapter                    int64
 123  server_dictation_percent           int64
 124  act_cnt_hour_21                    float64
 125  act_cnt_hour_20                    float64
 126  act_cnt_hour_23                    float64
 127  server_access                      float64
 128  server_outlink_percent             int64
 129  server_course_percent              int64
 130  browser_course_info_percent        int64
 131  browser_course                     int64
 132  browser_vertical_percent           int64
 133  sessions_in_week_1                 float64
 134  sessions_in_week_0                 float64
 135  sessions_in_week_3                 float64
 136  sessions_in_week_2                 float64
 137  sessions_in_week_4                 float64
 138  browser_about                      int64
dtypes: float64(90), int64(49)
memory usage: 127.8 MB

In [16]:
### Split the data set into an 80/20 random split for training and testing
#Creating the training data using train test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 100)

In [17]:
# Create function for short train test to condense the output 
## Technique from Data 6320

def shorttraintest(vartrain, vartest, y_train, y_test, model):

    #Fit the model
    model.fit(vartrain, y_train)

    #Predict with the model
    model_pred = model.predict(vartest)
    model_prob = model.predict_proba(vartest)


    print('Confusion Matrix:')
    print(confusion_matrix(y_test, model_pred))
    print("")

    #Assess with the model
    score = model.score(vartest, y_test)
    score_format = 'Accuracy Score: {0:.4f}'.format(score)
    print(score_format)

    recall = recall_score(y_test, model_pred)
    recall_format = 'Recall Score: {0:.4f}'.format(recall)
    print(recall_format)
    
    precision = precision_score(y_test, model_pred)
    precision_format = 'Precision Score: {0:.4f}'.format(precision)
    print(precision_format)
    
    # calculate roc curve
    y_pred_prob = model.predict_proba(vartest)[:,1]
    fpr, tpr, thresholds = roc_curve(y_test, y_pred_prob)
    roc_auc = roc_auc_score(y_test, y_pred_prob)
    roc_auc_format = 'ROC AUC Score: {0:.4f}'.format(roc_auc)
    print(roc_auc_format)
    print('')

### Model 1: Random Forest (RF)

In [18]:
#Running the Random Forest Model

vartrain = X_train
vartest = X_test
model = RandomForestClassifier()
shorttraintest(vartrain, vartest, y_train, y_test, model)

Confusion Matrix:
[[ 2911  2090]
 [  873 18235]]

Accuracy Score: 0.8771
Recall Score: 0.9543
Precision Score: 0.8972
ROC AUC Score: 0.8763

In [19]:
#Conducting 5 fold Cross Validation for Random Forest

cv_scores = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy')
cv_model = RandomForestClassifier() 

# Perform k-fold cross-validation (using 5 folds)
cv_scores = cross_val_score(cv_model, vartrain, y_train, cv=5, scoring='accuracy')

#Printing cv scores, mean and standard deviation for the model
##Co-pilot in VS Code assisted with code for printing mean and standard deviation
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard deviation: {cv_scores.std():.4f}")
print('CV Accuracy Scores:')
print(cv_scores)
print('')

KeyboardInterrupt:

### Model 2: XGBoost (XGB)

In [ ]:
#Running the XGB Model
vartrain = X_train
vartest = X_test
model =  XGBClassifier()

shorttraintest(vartrain, vartest, y_train, y_test, model)

Confusion Matrix:
[[ 2854  2147]
 [  856 18252]]

Accuracy Score: 0.8754
Recall Score: 0.9552
Precision Score: 0.8947
ROC AUC Score: 0.8812

In [ ]:
#Conducting 5 fold Cross Validation for XGB

cv_model = XGBClassifier()

# Perform k-fold cross-validation (using 5 folds)
cv_scores = cross_val_score(cv_model, vartrain, y_train, cv=5, scoring='accuracy')

#Printing cv scores, mean and standard deviation for the model
##Co-pilot in VS Code assisted with code for printing mean and standard deviation
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard deviation: {cv_scores.std():.4f}")
print('CV Accuracy Scores:')
print(cv_scores)
print('')

Cross-validation scores: [0.87281589 0.87006792 0.87530461 0.87695738 0.87410557]
Mean CV accuracy: 0.8739
Standard deviation: 0.0023
CV Accuracy Scores:
[0.87281589 0.87006792 0.87530461 0.87695738 0.87410557]

### Model 3: AdaBoost Classifier (AB)

In [ ]:
#Running the AdaBoost Classifier
vartrain = X_train
vartest = X_test
model = AdaBoostClassifier()

shorttraintest(vartrain, vartest, y_train, y_test, model)

c:\Users\autum\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Confusion Matrix:
[[ 2818  2183]
 [  754 18354]]

Accuracy Score: 0.8782
Recall Score: 0.9605
Precision Score: 0.8937
ROC AUC Score: 0.8803

In [ ]:
#Running 5 fold Cross Validation for AB
cv_model = AdaBoostClassifier()

# Perform k-fold cross-validation (using 5 folds)
cv_scores = cross_val_score(cv_model, vartrain, y_train, cv=5, scoring='accuracy')

#Printing cv scores, mean and standard deviation for the model
##Co-pilot in VS Code assisted with code for printing mean and standard deviation
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard deviation: {cv_scores.std():.4f}")
print('CV Accuracy Scores:')
print(cv_scores)
print('')

c:\Users\autum\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\autum\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\autum\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\autum\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\autum\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Cross-validation scores: [0.87514906 0.87395655 0.87810442 0.87623146 0.87685368]
Mean CV accuracy: 0.8761
Standard deviation: 0.0014
CV Accuracy Scores:
[0.87514906 0.87395655 0.87810442 0.87623146 0.87685368]

### Model 4: Decision Tree (DT)

In [ ]:
#Running the DecisionTree Classifier
vartrain = X_train
vartest = X_test
model = DecisionTreeClassifier()

shorttraintest(vartrain, vartest, y_train, y_test, model)

Confusion Matrix:
[[ 2777  2224]
 [ 2405 16703]]

Accuracy Score: 0.8080
Recall Score: 0.8741
Precision Score: 0.8825
ROC AUC Score: 0.7149

In [ ]:
#Running 5 fold Cross Validation for DT

cv_model = DecisionTreeClassifier()

# Perform k-fold cross-validation (using 5 folds)
cv_scores = cross_val_score(cv_model, vartrain, y_train, cv=5, scoring='accuracy')

#Printing cv scores, mean and standard deviation for the model
##Co-pilot in VS Code assisted with code for printing mean and standard deviation
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard deviation: {cv_scores.std():.4f}")
print('CV Accuracy Scores:')
print(cv_scores)
print('')

Cross-validation scores: [0.80188728 0.80655364 0.80764245 0.80939542 0.8037955 ]
Mean CV accuracy: 0.8059
Standard deviation: 0.0027
CV Accuracy Scores:
[0.80188728 0.80655364 0.80764245 0.80939542 0.8037955 ]

### Model 5: K-Neighbors (kNN)

In [ ]:
#Running the K-Neighbors Model
vartrain = X_train
vartest = X_test
model = KNeighborsClassifier()
shorttraintest(vartrain, vartest, y_train, y_test, model)

Confusion Matrix:
[[ 2249  2752]
 [  710 18398]]

Accuracy Score: 0.8564
Recall Score: 0.9628
Precision Score: 0.8699
ROC AUC Score: 0.8019

In [ ]:
#Running 5 fold Cross Validation for kNN

cv_model =  KNeighborsClassifier()

# Perform k-fold cross-validation (using 5 folds)
cv_scores = cross_val_score(cv_model, vartrain, y_train, cv=5, scoring='accuracy')

#Printing cv scores, mean and standard deviation for the model
##Co-pilot in VS Code assisted with code for printing mean and standard deviation
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard deviation: {cv_scores.std():.4f}")
print('CV Accuracy Scores:')
print(cv_scores)
print('')

Cross-validation scores: [0.85243947 0.85218023 0.85243947 0.85372809 0.85367624]
Mean CV accuracy: 0.8529
Standard deviation: 0.0007
CV Accuracy Scores:
[0.85243947 0.85218023 0.85243947 0.85372809 0.85367624]

### Model 6: Logistic Regression (LR)

In [ ]:
#Running 5 fold Cross Validation LR
vartrain = X_train
vartest = X_test
model = LogisticRegression()

shorttraintest(vartrain, vartest, y_train, y_test, model)

Confusion Matrix:
[[ 2585  2416]
 [  655 18453]]

Accuracy Score: 0.8726
Recall Score: 0.9657
Precision Score: 0.8842
ROC AUC Score: 0.8783

In [ ]:
#Running 5 fold Cross Validation for LR

cv_model =  LogisticRegression()

# Perform k-fold cross-validation (using 5 folds)
cv_scores = cross_val_score(cv_model, vartrain, y_train, cv=5, scoring='accuracy')

#Printing cv scores, mean and standard deviation for the model
##Co-pilot in VS Code assisted with code for printing mean and standard deviation
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard deviation: {cv_scores.std():.4f}")
print('CV Accuracy Scores:')
print(cv_scores)
print('')

Cross-validation scores: [0.87183077 0.86980868 0.87597864 0.8732241  0.87296484]
Mean CV accuracy: 0.8728
Standard deviation: 0.0020
CV Accuracy Scores:
[0.87183077 0.86980868 0.87597864 0.8732241  0.87296484]

### Model 7: Linear Discriminate Analysis (LDA)

In [ ]:
#Running the Model for LDA

vartrain = X_train
vartest = X_test
model =LinearDiscriminantAnalysis()

shorttraintest(vartrain, vartest, y_train, y_test, model)

Confusion Matrix:
[[ 2462  2539]
 [  593 18515]]

Accuracy Score: 0.8701
Recall Score: 0.9690
Precision Score: 0.8794
ROC AUC Score: 0.8726

In [ ]:
#Running 5 fold Cross Validation for LDA

cv_model = LinearDiscriminantAnalysis()

# Perform k-fold cross-validation (using 5 folds)
cv_scores = cross_val_score(cv_model, vartrain, y_train, cv=5, scoring='accuracy')

#Printing cv scores, mean and standard deviation for the model
##Co-pilot in VS Code assisted with code for printing mean and standard deviation
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard deviation: {cv_scores.std():.4f}")
print('CV Accuracy Scores:')
print(cv_scores)
print('')

Cross-validation scores: [0.86830508 0.86664593 0.87364546 0.86959452 0.87016489]
Mean CV accuracy: 0.8697
Standard deviation: 0.0023
CV Accuracy Scores:
[0.86830508 0.86664593 0.87364546 0.86959452 0.87016489]

### Model 8: Naïve Bayes Classifier (NB)

In [ ]:
#Running the Model for NB

vartrain = X_train
vartest = X_test
model = GaussianNB()

shorttraintest(vartrain, vartest, y_train, y_test, model)

Confusion Matrix:
[[ 2763  2238]
 [ 1381 17727]]

Accuracy Score: 0.8499
Recall Score: 0.9277
Precision Score: 0.8879
ROC AUC Score: 0.7737

In [ ]:
#Running 5 fold Cross Validation for NB

cv_model =  GaussianNB()

# Perform k-fold cross-validation (using 5 folds)
cv_scores = cross_val_score(cv_model, vartrain, y_train, cv=5, scoring='accuracy')

#Printing cv scores, mean and standard deviation for the model
##Co-pilot in VS Code assisted with code for printing mean and standard deviation
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard deviation: {cv_scores.std():.4f}")
print('CV Accuracy Scores:')
print(cv_scores)
print('')

Cross-validation scores: [0.84839529 0.8480842  0.85487634 0.8514985  0.85253552]
Mean CV accuracy: 0.8511
Standard deviation: 0.0026
CV Accuracy Scores:
[0.84839529 0.8480842  0.85487634 0.8514985  0.85253552]

### Model 9: Support Vector Machine (SVM)
- Running this model last due to computational power needed
- Sampling a subset of the data due to run time of the full data creating issues and timing out

In [ ]:
#Running model with a sample of the data for managability
##Used Anaconda Assistant for help with figuring out my run time issue and providing the sampling code
vartrain = X_train.sample(frac=0.1, random_state=42)
vartest = X_test
model = SVC()

shorttraintest(vartrain, vartest, y_train, y_test, model)

ValueError: Found input variables with inconsistent numbers of samples: [9643, 96433]

In [ ]:
#Entered Output Error into Anaconda Assistant and am running the code provided

# Define input variables - using only 10% of training data to make computation manageable
# Sample both X_train and y_train with the same indices to maintain alignment
train_indices = X_train.sample(frac=0.1, random_state=42).index
vartrain = X_train.loc[train_indices]
y_train_sampled = y_train.loc[train_indices]  # Assuming y_train is a pandas Series/DataFrame

# Keep test data as is
vartest = X_test

# Initialize Support Vector Machine Classifier
model = SVC()

# Use the sampled training data with corresponding sampled labels
shorttraintest(vartrain, vartest, y_train_sampled, y_test, model)

AttributeError: This 'SVC' has no attribute 'predict_proba'

In [ ]:
#Entered Output Error into Anaconda Assistant and am running the code provided

# Define input variables - using only 10% of training data to make computation manageable
# Sample both X_train and y_train with the same indices to maintain alignment
train_indices = X_train.sample(frac=0.1, random_state=42).index
vartrain = X_train.loc[train_indices]
y_train_sampled = y_train.loc[train_indices]  # Assuming y_train is a pandas Series/DataFrame

# Keep test data as is
vartest = X_test

# Initialize Support Vector Machine Classifier with probability=True
# This enables the predict_proba method that the shorttraintest function is trying to use
model = SVC(probability=True)

# Use the sampled training data with corresponding sampled labels
shorttraintest(vartrain, vartest, y_train_sampled, y_test, model)

Confusion Matrix:
[[ 2604  2397]
 [  813 18295]]

Accuracy Score: 0.8669
Recall Score: 0.9575
Precision Score: 0.8842
ROC AUC Score: 0.8298

In [ ]:
# Cross-validation on the sampled data
#Created with the Anaconda Assistant to ensure(hopefully) proper execution of  cross validation with sample data

# Define the model for cross-validation
cv_model = SVC(probability=True)

# Perform k-fold cross-validation (using 5 folds)
cv_scores = cross_val_score(cv_model, vartrain, y_train_sampled, cv=5, scoring='accuracy')

# Print cross-validation results
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {cv_scores.mean():.4f}")
print(f"Standard deviation: {cv_scores.std():.4f}")

Cross-validation scores: [0.85743909 0.86832556 0.8750648  0.86255187 0.8620332 ]
Mean CV accuracy: 0.8651
Standard deviation: 0.0061

In [ ]:
#Creating a Dataframe for all modelw
##Created with co-pilot in VS Code

# Define a dictionary to store the results
cv_results = {
    "Model": [],
    "CV Scores": [],
    "Mean Accuracy": [],
    "Standard Deviation": []
}

# Add results for each model (example for Random Forest)
cv_results["Model"].append("Random Forest")
cv_results["CV Scores"].append(cv_scores)  # Use the cv_scores from your Random Forest cross-validation
cv_results["Mean Accuracy"].append(cv_scores.mean())
cv_results["Standard Deviation"].append(cv_scores.std())

# Repeat for other models...

# Create a DataFrame from the results
cv_results_df = pd.DataFrame(cv_results)

# Display the DataFrame
cv_results_df

,Model,CV Scores,Mean Accuracy,Standard Deviation
0,Random Forest,"[0.8574390876101607, 0.8683255572835666, 0.875...",0.865083,0.006071